### ISSUE TITLE
Error on record bulk attendance

### ISSUE THREAD

**Issue by simonbharrison1** [anthonygoslar/LMS-Support#88] opened 2021-02-15 15:04 UTC
on fetch results.  Error message in live, hanging on dev
![image](https://user-images.githubusercontent.com/77050948/107962679-e82aa180-6faf-11eb-9345-34291c0aa0e3.png)

**Comment by anthonygoslar** [comment] 2021-02-17 08:22
Duplicate of #70. It's been corrected on the dev server ready for testing and deployment.

**Closed by anthonygoslar** 2021-02-17 08:22 UTC
